### ISSUE TITLE
Airview only supports video streams

### ISSUE THREAD

**Issue by ghost** [nto/AirView#2]
Feature request:
It would be most excellent if Airview also supported audio-only streams.  
Currently it only supports video.

**Comment by matdumsa** [comment]
+1

**Comment by ckolderup** [comment]
Yes, supporting audio-only + background audio (for audio streams) would be totally killer. I could switch to the Remote app to control my music and have it stream to wherever I am in the house.

**Comment by gsr** [comment]
Agreed, It'd be great to start a podcast or playlist on my computer and then walk away to the kitchen to make dinner and have it play on my iphone/earbuds seamlessly.

**Comment by jeanregisser** [comment]
Audio streaming is now possible since the private key has been cracked.
See working implementation: https://github.com/bbhoss/shairport

**Comment by nto** [comment]
Check out AirSpeaker, which I just pushed. Note that it is not finished (no multitasking yet).
