### ISSUE TITLE
iTunes is not showing iPhone as an option

### ISSUE THREAD

**Issue by MNLBCK** [nto/AirView#4]
Hello.

When activating Airview on my iPhone 4 the AirPlay icon on the right bottom corner of my Windows iTunes 10.1.2.17 shows up. However, clicking on it only shows one option: "My Computer".
When shutting down AirView, the icon in iTunes disappears.

How can I select my iPhone in order to stream audio or video content to it?

Btw: Is background audio streaming supported by AirView/AirPlay?

**Comment by nto** [comment]
Use the AirPlay icon which appears in the movie controller when playing a movie in iTunes.

As for audio support, check out AirSpeaker, it supports audio streaming, but it is not finished yet.
https://github.com/nto/AirSpeaker
